### ISSUE TITLE
Provide Sourcecode

### ISSUE THREAD

**Issue by Kaligule** [levithomason/cmatrix#1]
Please provide the source code of this programm, since the [original](http://asty.org/cmatrix/) is licensed under GPL, wich states:

> For example, if you distribute copies of such a program, whether
> gratis or for a fee, you must give the recipients all the rights that
> you have.  **You must make sure that they, too, receive or can get the
> source code**.  And you must show them these terms so they know their
> rights.

**Comment by levithomason** [comment]
There she be!  Let me konw if you get it to work.  Most the links I found for the current source and instructions are all broken.  Since, you know, the last release was 13+ years ago :)

[src](https://github.com/levithomason/cmatrix/tree/master/src)

**Comment by Kaligule** [comment]
Thank you. This was quick :)

**Comment by levithomason** [comment]
Not a problem, thanks for pointing that out.
