### ISSUE TITLE
cmatrix does not work well in iTerm2, HyperTerm

### ISSUE THREAD

**Issue by sachin21** [levithomason/cmatrix#2]
This is the frame rate issue.
Would you optimize the speed of drawing?
# Reproduced environment

I'm using
- Display Size: 13-inch MacBook Air
- CPU: 1.6 GHz Intel Core i5
- RAM: 8GB
- Graphics: Intel HD Graphics 6000 1536 MB
- CMatrix version: CMatrix version 1.2a
- Emulator: iTerm2, HyperTerm

**Comment by levithomason** [comment]
Sorry, I don't have the source code for this. It is just a binary I retrieved from an old Mac ports project. It's not my project. I only reposted it here as is for fun.

**Comment by sachin21** [comment]
I see. Thank you for the quick response.
